CREATE TABLE mountains(id INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
name VARCHAR(50));

CREATE TABLE peaks(id INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
name VARCHAR(50),
mountain_id INT(11) NOT NULL,
CONSTRAINT FK_mountain_id FOREIGN KEY (mountain_id)
REFERENCES mountains(id) ON DELETE CASCADE);