CREATE TABLE mountains (id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(50) NOT NULL);

CREATE TABLE peaks(id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(50) NOT NULL,
mountain_id INT(11),
CONSTRAINT FK_mountain_id FOREIGN KEY (mountain_id)
REFERENCES mountains(id));